=== Adaylla/pos-2025-tarefas/xsd/cardapio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:c="http://cardapio.org"
        targetNamespace="http://cardapio.org"
        elementFormDefault="qualified">

    <element name="nome" type="string"/>
    <element name="descricao" type="string"/>
    <element name="ingredientes" type="string"/>
    <element name="tempoPreparo" type="string"/>
    <element name="calorias" type="string"/>
    <element name="preco">
        <simpleType>
            <restriction base="string">
                <pattern value="R\$[0-9]+(,[0-9]{2})?"/>
            </restriction>
        </simpleType>
    </element>

    <element name="cardapio">
        <complexType>
            <sequence>
                <element ref="c:prato" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="prato">
        <complexType>
            <sequence>
                <element ref="c:nome"/>
                <element ref="c:descricao"/>
                <element ref="c:ingredientes"/>
                <element ref="c:preco"/>
                <element ref="c:calorias"/>
                <element ref="c:tempoPreparo"/>
            </sequence>
            <attribute name="id" type="string"/>
        </complexType>
    </element>
</schema>

=== Adaylla/pos-2025-tarefas/xsd/cardapio.xml
<?xml version="1.0" encoding="utf-8"?>
<cardapio xmlns="http://cardapio.org"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://cardapio.org cardapio.xsd">

    <prato id="P01">
        <nome>
            Feijoada
        </nome>
        <descricao>Esse é um prato tradicional do nosso cardápio.</descricao>
        <ingredientes>
            Feijão, Arroz, Carne e Coentro
        </ingredientes>
        <preco>R$35,00</preco>
        <calorias>670Kcal</calorias>
        <tempoPreparo>35 minutos</tempoPreparo>
    </prato>

    <prato id="P02">
        <nome>
            File com Fritas
        </nome>
        <descricao>Esse é um prato top 2 do nosso cardápio.</descricao>
        <ingredientes>
            Carne de Sol, cebola, óleo e batata frita.
        </ingredientes>
        <preco>R$58,00</preco>
        <calorias>890Kcal</calorias>
        <tempoPreparo>20 minutos</tempoPreparo>
    </prato>

    <prato id="P03">
        <nome>
            Macarrão no molho branco
        </nome>
        <descricao>Prato mais pedido.</descricao>
        <ingredientes>
           Macarrão, Creme de leite, manteiga e cebola.
        </ingredientes>
        <preco>R$40,00</preco>
        <calorias>570Kcal</calorias>
        <tempoPreparo>35 minutos</tempoPreparo>
    </prato>

    <prato id="P04">
        <nome>
            Carne no molho madeira
        </nome>
        <descricao>Novidade no nosso cardápio.</descricao>
        <ingredientes>
            Carne, molho madeira pronto e creme de leite. 
        </ingredientes>
        <preco>R$30,00</preco>
        <calorias>520Kcal</calorias>
        <tempoPreparo>40 minutos</tempoPreparo>
    </prato>

    <prato id="P05">
        <nome>
            Almoço
        </nome>
        <descricao>Esse é o prato favorito do nosso cardápio.</descricao>
        <ingredientes>
            Feijão, Arroz, Farofa e Carne.
        </ingredientes>
        <preco>R$15,00</preco>
        <calorias>450Kcal</calorias>
        <tempoPreparo>20 minutos</tempoPreparo>
    </prato>

</cardapio>
